encrypt.settings.profile_keys:
  type: sequence
  label: 'Encryption Profile Keys'
  sequence:
    type: mapping
    mapping:
      encryption_profile:
        type: string
        label: 'Encryption profile'
      encryption_key:
        type: string
        label: 'Encryption profile key'