encrypt.encryption_configuration.*:
  type: config_entity
  label: 'Encrypt Configuration'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    encryption_method:
      type: string
      label: 'Encryption method selected for encryption config'
    service_default:
      type: boolean
      label: 'Yes/no if encryption configuration is the default'
